/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokudesktopapp;

import java.awt.Color;

/**
 * Custom JPanel class that is used for the Getting Started panel.
 * This panel is visible when the application is first loaded.
 * @author Steve
 */
public class GettingStartedPanel extends javax.swing.JPanel {

    /**
     * Default constructor.
     * Creates new form GettingStartedPanel
     * @param GUIHandler the guiHandler that controls all components
     */
    public GettingStartedPanel(GUIHandler guiHandler) {
        this.myGuiHandler = guiHandler; //save the instance of the guiHandler
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        gettingStartedLabel = new javax.swing.JLabel();
        newUserLabel = new javax.swing.JLabel();
        logInLabel = new javax.swing.JLabel();
        playSudokuLabel = new javax.swing.JLabel();
        showRulesLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(193, 220, 255));
        setBorder(new javax.swing.border.MatteBorder(null));
        setPreferredSize(new java.awt.Dimension(250, 300));
        setLayout(new java.awt.GridBagLayout());

        gettingStartedLabel.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        gettingStartedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gettingStartedLabel.setText("Getting Started");
        gettingStartedLabel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(gettingStartedLabel, gridBagConstraints);
        gettingStartedLabel.getAccessibleContext().setAccessibleName("GettingStartedLabel");

        newUserLabel.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        newUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        newUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newUserLabel.setText("New User");
        newUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newUserClick(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newUserLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newUserLabelMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(newUserLabel, gridBagConstraints);
        newUserLabel.getAccessibleContext().setAccessibleName("NewUserLabel");

        logInLabel.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        logInLabel.setForeground(new java.awt.Color(255, 255, 255));
        logInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logInLabel.setText("Log In");
        logInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logInLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logInLabelMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(logInLabel, gridBagConstraints);

        playSudokuLabel.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        playSudokuLabel.setForeground(new java.awt.Color(255, 255, 255));
        playSudokuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playSudokuLabel.setText("Play Sudoku");
        playSudokuLabel.setToolTipText("Play sudoku anonymously");
        playSudokuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playSudokuAnonymouslyClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playSudokuLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playSudokuLabelMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(playSudokuLabel, gridBagConstraints);

        showRulesLabel.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        showRulesLabel.setForeground(new java.awt.Color(255, 255, 255));
        showRulesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showRulesLabel.setText("Show Sudoku Rules");
        showRulesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSudokuRulesClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showRulesLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showRulesLabelMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(showRulesLabel, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 8;
        add(jSeparator1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handling for the "New User" JLabel.
     * Shows the NewUserPanel in sidebar.
     * @param evt MouseEvent
     */
    private void newUserClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserClick
        // this will redirect you to a JFrame To Add a new user
        this.myGuiHandler.showAddNewUserPanel();
    }//GEN-LAST:event_newUserClick

    /**
     * Event handling for the "Log in" JLabel.
     * Shows the LogInPanel in sidebar.
     * @param evt MouseEvent
     */
    private void logInClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInClicked
        // this will redirect you to a JPanel to choose with which nickname to log in
        this.myGuiHandler.showLogInPanel();
        
    }//GEN-LAST:event_logInClicked

    /**
     * Event handling for playing a sudoku anonymously
     * Shows the NewGameOptionsPanel to the sidebar.
     * @param evt MouseEvent
     */
    private void playSudokuAnonymouslyClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playSudokuAnonymouslyClicked
        // this will redirect you to a JFrame selecting options for the sudoku
        myGuiHandler.showNewGameOptionsPanel();
    }//GEN-LAST:event_playSudokuAnonymouslyClicked

    /**
     * Event handling for the "Show Rules" JLabel
     * Shows SudokuHelpDialog.
     * @param evt 
     */
    private void showSudokuRulesClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSudokuRulesClicked
        // this will open up a JPanel showing help from a file for sudoku
        myGuiHandler.showHelpDialog();
    }//GEN-LAST:event_showSudokuRulesClicked

    /**
     * Event handling for hovering over the JLabel of New User(entering)
     * @param evt 
     */
    private void newUserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserLabelMouseEntered
        // TODO add your handling code here:
        this.newUserLabel.setForeground(alternativeFontColor);
    }//GEN-LAST:event_newUserLabelMouseEntered
    /**
     * Event handling for hovering over the JLabel of New User(exiting)
     * @param evt 
     */
    private void newUserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserLabelMouseExited
        // TODO add your handling code here:
        this.newUserLabel.setForeground(defaultFontColor);
        
    }//GEN-LAST:event_newUserLabelMouseExited

    /**
     * Event handling for hovering over the JLabel of Log in (entering)
     * @param evt 
     */
    private void logInLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInLabelMouseEntered
        // TODO add your handling code here:
        this.logInLabel.setForeground(alternativeFontColor);
    }//GEN-LAST:event_logInLabelMouseEntered

    /**
     * Event handling for hovering over the JLabel of Log in (exiting)
     * @param evt 
     */
    private void logInLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInLabelMouseExited
        // TODO add your handling code here:
        this.logInLabel.setForeground(defaultFontColor);
    }//GEN-LAST:event_logInLabelMouseExited

    /**
     * Event handling for hovering over the JLabel of playing sudoku (entering)
     * @param evt 
     */
    private void playSudokuLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playSudokuLabelMouseEntered
        // TODO add your handling code here:
        this.playSudokuLabel.setForeground(alternativeFontColor);
    }//GEN-LAST:event_playSudokuLabelMouseEntered

    /**
     * Event handling for hovering over the JLabel of playing Sudoku (exiting)
     * @param evt 
     */
    private void playSudokuLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playSudokuLabelMouseExited
        // TODO add your handling code here:
        this.playSudokuLabel.setForeground(defaultFontColor);
    }//GEN-LAST:event_playSudokuLabelMouseExited

    /**
     * Event handling for hovering over the JLabel of Show Rules (entering)
     * @param evt 
     */
    private void showRulesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showRulesLabelMouseEntered
        // TODO add your handling code here:
        this.showRulesLabel.setForeground(alternativeFontColor);
    }//GEN-LAST:event_showRulesLabelMouseEntered

    /**
     * Event handling for hovering over the JLabel of Show Rules (exiting)
     * @param evt 
     */
    private void showRulesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showRulesLabelMouseExited
        // TODO add your handling code here:
        this.showRulesLabel.setForeground(defaultFontColor);
    }//GEN-LAST:event_showRulesLabelMouseExited

    
    /**
     * Color constant for JLabels.
     */
    private static final Color defaultFontColor = new Color(255, 255, 255);
    /**
     * Color constant for hovered over JLabels.
     */
    private static final Color alternativeFontColor = new Color(204, 204, 204);
    /**
     * An instance of the GUIHandler.
     */
    private GUIHandler myGuiHandler;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gettingStartedLabel;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JLabel newUserLabel;
    private javax.swing.JLabel playSudokuLabel;
    private javax.swing.JLabel showRulesLabel;
    // End of variables declaration//GEN-END:variables
}
