/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokudesktopapp;

import java.awt.Color;

/**
 *
 * @author Steve
 */
public class LoggedInPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoggedInPanel
     */
    public LoggedInPanel(GUIHandler guiHandler) {
        this.myGuiHandler = guiHandler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        optionsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        continueLastGameLabel = new javax.swing.JLabel();
        newGameLabel = new javax.swing.JLabel();
        showStatsLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(193, 220, 255));
        setPreferredSize(new java.awt.Dimension(250, 300));
        setLayout(new java.awt.GridBagLayout());

        optionsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        optionsLabel.setText("Options");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        add(optionsLabel, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 2;
        add(jSeparator1, gridBagConstraints);

        continueLastGameLabel.setForeground(new java.awt.Color(255, 255, 255));
        continueLastGameLabel.setText("Continue Last Game");
        continueLastGameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueLastGameLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continueLastGameLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                continueLastGameLabelMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(continueLastGameLabel, gridBagConstraints);

        newGameLabel.setForeground(new java.awt.Color(255, 255, 255));
        newGameLabel.setText("New Game");
        newGameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newGameLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newGameLabelMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(newGameLabel, gridBagConstraints);

        showStatsLabel.setForeground(new java.awt.Color(255, 255, 255));
        showStatsLabel.setText("Show Statistics");
        showStatsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showStatsLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showStatsLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showStatsLabelMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(showStatsLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void continueLastGameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueLastGameLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_continueLastGameLabelMouseClicked

    private void newGameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameLabelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_newGameLabelMouseClicked

    private void showStatsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showStatsLabelMouseClicked
        // TODO add your handling code here:
        this.myGuiHandler.showStatsPanel();
    }//GEN-LAST:event_showStatsLabelMouseClicked

    private void continueLastGameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueLastGameLabelMouseEntered
        this.continueLastGameLabel.setForeground(alternativeFontColor);
    }//GEN-LAST:event_continueLastGameLabelMouseEntered

    private void continueLastGameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueLastGameLabelMouseExited
        // TODO add your handling code here:
        this.continueLastGameLabel.setForeground(defaultFontColor);
    }//GEN-LAST:event_continueLastGameLabelMouseExited

    private void newGameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameLabelMouseEntered
        this.newGameLabel.setForeground(alternativeFontColor);
    }//GEN-LAST:event_newGameLabelMouseEntered

    private void newGameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameLabelMouseExited
        this.newGameLabel.setForeground(defaultFontColor);
    }//GEN-LAST:event_newGameLabelMouseExited

    private void showStatsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showStatsLabelMouseEntered
        this.showStatsLabel.setForeground(alternativeFontColor);
    }//GEN-LAST:event_showStatsLabelMouseEntered

    private void showStatsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showStatsLabelMouseExited
        this.showStatsLabel.setForeground(defaultFontColor);
    }//GEN-LAST:event_showStatsLabelMouseExited

    
    private static final Color defaultFontColor = new Color(255, 255, 255);
    private static final Color alternativeFontColor = new Color(204, 204, 204);
    GUIHandler myGuiHandler;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel continueLastGameLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel newGameLabel;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JLabel showStatsLabel;
    // End of variables declaration//GEN-END:variables
}
