/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokudesktopapp;

import Logic.Users.Person;
import java.util.ArrayList;

/**
 *
 * @author Steve
 */
public class LogInPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogInPanel
     */
    public LogInPanel(GUIHandler guiHandler) {
        this.myGuiHandler = guiHandler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        searchPanel = new javax.swing.JPanel();
        nicknameSearchInput = new javax.swing.JTextField();
        searchIconLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsJList = new javax.swing.JList();
        loginLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setLayout(new java.awt.GridBagLayout());

        nicknameSearchInput.setText("nickname");
        nicknameSearchInput.setToolTipText("Enter nickname to search");
        nicknameSearchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameSearchInputActionPerformed(evt);
            }
        });

        searchIconLabel.setText("[icon here]");

        org.jdesktop.layout.GroupLayout searchPanelLayout = new org.jdesktop.layout.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(searchPanelLayout.createSequentialGroup()
                .add(searchIconLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nicknameSearchInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 401, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 146, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, searchPanelLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchIconLabel)
                    .add(nicknameSearchInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(searchPanel, gridBagConstraints);

        jScrollPane1.setBackground(new java.awt.Color(192, 192, 192));

        resultsJList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        resultsJList.setModel(new javax.swing.AbstractListModel()
            {
                ArrayList<Person> listToShow = resultsToShare;
                public int getSize() {return listToShow.size();}
                public Object getElementAt(int i) {return listToShow.get(i);}
            });
            resultsJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            resultsJList.setToolTipText("Choose among results");
            jScrollPane1.setViewportView(resultsJList);

            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 3;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints.ipady = 4;
            gridBagConstraints.weightx = 0.3;
            gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
            add(jScrollPane1, gridBagConstraints);

            loginLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
            loginLabel.setText("Log In");
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 0;
            gridBagConstraints.ipady = 10;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
            add(loginLabel, gridBagConstraints);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 1;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            add(jSeparator2, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents

    private void nicknameSearchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameSearchInputActionPerformed
        // search nickname on the db and return results
        ArrayList<Person> results;
        results = this.myGuiHandler.searchByNickname(this.nicknameSearchInput.getText());
        if (results != null)
        {
            this.resultsToShare = results;
        }
        else
        {
            this.resultsToShare = new ArrayList<>();
        }
    }//GEN-LAST:event_nicknameSearchInputActionPerformed

    private GUIHandler myGuiHandler;
    private ArrayList<Person> resultsToShare;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField nicknameSearchInput;
    private javax.swing.JList resultsJList;
    private javax.swing.JLabel searchIconLabel;
    private javax.swing.JPanel searchPanel;
    // End of variables declaration//GEN-END:variables
}
