/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package sudokudesktopapp;

/**
 * Custom JPanel class used to create a new user.
 * It is loaded in the mainpanel of the application.
 * @author Steve
 */
public class NewUserPanel extends javax.swing.JPanel {

    /**
     * Default constructor.
     * Creates new form NewUserPanel
     */
    public NewUserPanel(GUIHandler guiHandler) {
        this.myGuiHandler = guiHandler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nicknameEnterPanel = new javax.swing.JPanel();
        nicknameLabel = new javax.swing.JLabel();
        nicknameInput = new javax.swing.JTextField();
        buttonsPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(0, 1));

        nicknameEnterPanel.setPreferredSize(new java.awt.Dimension(100, 38));
        nicknameEnterPanel.setSize(new java.awt.Dimension(100, 100));
        nicknameEnterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 5));

        nicknameLabel.setText("Nickname:");
        nicknameEnterPanel.add(nicknameLabel);

        nicknameInput.setText("Enter a nickname");
        nicknameInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nicknameInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onTextFieldEntered(evt);
            }
        });
        nicknameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEnterPressed(evt);
            }
        });
        nicknameEnterPanel.add(nicknameInput);

        add(nicknameEnterPanel);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout buttonsPanelLayout = new org.jdesktop.layout.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .add(okButton)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(okButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(buttonsPanel);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handling for when the user cliks on the TextField.
     * Clears the value, so that they can write something else.
     * @param evt 
     */
    private void onTextFieldEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onTextFieldEntered
        // TODO add your handling code here:
        this.nicknameInput.setText("");
    }//GEN-LAST:event_onTextFieldEntered

    /**
     * Event handling for pressing Enter key after typing.
     * Creates a new user in the PersonDB, using the nickname provided.
     * @param evt 
     */
    private void onEnterPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEnterPressed
        this.myGuiHandler.addNewUser(this.nicknameInput.getText());
        this.myGuiHandler.hideAddNewUserPanel();
    }//GEN-LAST:event_onEnterPressed

    /**
     * Event handling for clicking the ok button after typing.
     * Creates a new user in the PersonDB, using the nickname provided.
     * @param evt 
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.myGuiHandler.addNewUser(this.nicknameInput.getText());
        this.myGuiHandler.hideAddNewUserPanel();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Instance of the GUIHandler controller.
     */
    private GUIHandler myGuiHandler;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel nicknameEnterPanel;
    private javax.swing.JTextField nicknameInput;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
