/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokudesktopapp;

import Logic.Users.Person;

/**
 * Custom JPanel classed used for showing user's statistics.
 * It is loaded in the main panel, when prompted.
 * @author Steve
 */
public class StatsPanel extends javax.swing.JPanel {

    /**
     * Default constructor.
     * Creates new form StatsPanel
     */
    public StatsPanel(GUIHandler guiHandler, Person p) {
        this.myGuiHandler = guiHandler;
        this.player = p;
        initComponents();
        updateUIToPlayerStats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gamesPlayedTitleLabel = new javax.swing.JLabel();
        defeatsLabel = new javax.swing.JLabel();
        victoriesTitleLabel = new javax.swing.JLabel();
        victoriesLabel = new javax.swing.JLabel();
        defeatsTitleLabel = new javax.swing.JLabel();
        gamesPlayedLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        aliasPanel = new javax.swing.JPanel();
        aliasLabel = new javax.swing.JLabel();
        nicknameLabel = new javax.swing.JLabel();
        clearAllButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setLayout(new java.awt.GridBagLayout());

        gamesPlayedTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        gamesPlayedTitleLabel.setText("Games Played:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(gamesPlayedTitleLabel, gridBagConstraints);

        defeatsLabel.setText("gameDefeats");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(defeatsLabel, gridBagConstraints);

        victoriesTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        victoriesTitleLabel.setText("Victories:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(victoriesTitleLabel, gridBagConstraints);

        victoriesLabel.setText("gameVictories");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(victoriesLabel, gridBagConstraints);

        defeatsTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        defeatsTitleLabel.setText("Defeats:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(defeatsTitleLabel, gridBagConstraints);

        gamesPlayedLabel.setText("gamesPlayed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(gamesPlayedLabel, gridBagConstraints);
        add(jSeparator1, new java.awt.GridBagConstraints());

        aliasLabel.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        aliasLabel.setText("Alias:");
        aliasPanel.add(aliasLabel);

        nicknameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        nicknameLabel.setText("aliasName");
        aliasPanel.add(nicknameLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(aliasPanel, gridBagConstraints);

        clearAllButton.setText("Reset");
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 15;
        add(clearAllButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        add(jSeparator3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handling for clicking on "Reset". 
     * User's stats are erased from the PersonDB.
     * @param evt 
     */
    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        // TODO add your handling code here:
        if (this.player != null)
        {
            player.reset();
            updateUIToPlayerStats();
        }
    }//GEN-LAST:event_clearAllButtonActionPerformed

    /**
     * Helper function, populating this panel's fields to the person's properties.
     */
    private void updateUIToPlayerStats()
    {
        if (player!=null)
        {
            // populate the fields
            this.nicknameLabel.setText(player.getNickname());
            this.gamesPlayedLabel.setText(String.valueOf(player.getGamesPlayed()));
            this.victoriesLabel.setText(String.valueOf(player.getVictories()));
            this.defeatsLabel.setText(String.valueOf(player.getDefeats()));
        }
    }
    
    /**
     * Instance of the GUIHandler controller.
     */
    private GUIHandler myGuiHandler;
    /**
     * Instance of the Person object that has logged in the application.
     */
    private Person player;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aliasLabel;
    private javax.swing.JPanel aliasPanel;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JLabel defeatsLabel;
    private javax.swing.JLabel defeatsTitleLabel;
    private javax.swing.JLabel gamesPlayedLabel;
    private javax.swing.JLabel gamesPlayedTitleLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JLabel victoriesLabel;
    private javax.swing.JLabel victoriesTitleLabel;
    // End of variables declaration//GEN-END:variables
}
